### ISSUE TITLE
Testing updates to ARI codec for latest internet draft

### ISSUE THREAD

**Issue by mfarina1** [JHUAPL-DTNMA/dtnma-ace#6]
See Justin Ethier's ARI testing work in the dtnma-tools repo because the work he's done can effectively be copied and pasted for this ticket

**Comment by BrianSipos** [comment]
The original test cases are the `test_ari_*.c` files from [dtnma-tools](https://github.com/JHUAPL-DTNMA/dtnma-tools/tree/ari-handling-updates/test/cace) with associated test functions and cases.
\
These will be copied into the similarly named `test_ari_*.py` files from [ACE tests](https://github.com/JHUAPL-DTNMA/dtnma-ace/tree/apl-fy24/tests) with similar functions and input cases (defined as python arrays rather than C macros).

**Comment by justinethier** [comment]
Closing, changes have been merged.
